version: '3'
services:
  web:
    image: zagsdev/radius_sys:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=172.23.231.75
      - POSTGRES_DB=gildesecops
      - POSTGRES_USER=radiususer
      - POSTGRES_PASSWORD=radiuspassword
